# Book settings
title: scvi-tools manuscript reproducibility
author: Adam Gayoso, Romain Lopez, Galen Xing, et al.

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/yoseflab/scvi-tools-reproducibility  # Online location of your book

html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  colab_url: "https://colab.research.google.com"


parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution