---
site_name: scvi-tools-reproducibility
repo_url: https://github.com/yoseflab/scvi-tools-reproducibility
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: white
nav:
    - Home: 'index.md'
    - Figure 2 Multiple Covariates: 'scvi_covariates.ipynb'
    - Figure 3 totalVI scArches: 'scarches_totalvi_seurat_data.ipynb'
    - Figure 5 Stereoscope: 'Stereoscope.ipynb'
    - Supplement CellAssign: 'cell_assign_hgsc_and_follicular_data.ipynb'
plugins:
  - mkdocs-jupyter:
      include_source: True