name: Build and Deploy
on:
  push:
    # NOTE:
    #   For a **project** site (username.github.io/project/), push things
    #     to the **master** branch and make sure to set the line below to
    # `   - master`; also, at the end of the file, change to `BRANCH: gh-pages`
    #
    #   For a **personal** site (username.github.io/), push things to a **dev**
    #     branch  and make sure to set the line  below to `- dev` this is
    #     because for user pages GitHub pages **requires** the deployment to be
    #     on the master branch; also, at the end of the file, change to
    #    `BRANCH: master`
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install dependencies
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -U pip && pip install jupyter-book && pip install sphinxcontrib-gtagjs

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build .

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: pages # The branch the action should deploy to.
          FOLDER: ./_build/html # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch